name: render
variables:
  - name: book_id
    value: 6a482f452173e8caf0d09db0
  - name: book_endpoint
    value: book
  - name: app_url
    value: https://learning-node-swhj.onrender.com
  - name: locale
    value: ru
